auto:	          true

markdown:         rdiscount
pygments:         true
paginate:         6
permalink:        /:title

title:            chentc.info
url:              http://chentc.infofeed:             /atom.xml
author:
    name:         BeiYuu
    twitter:      twitter.com/beiyuu
description:      "Finley Chen\'s Blog"
author_info:      <a href="http://about.me/fanglin.chen">Finley Chen</a>

copyright:
    - Design by <a href="http://about.me/fanglin.chen" title="Finley Chen" target="_blank">BeiYuu</a> &copy; Copyright 2012
